name: thamn
description: description_project_x
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #-------------------------------------
  ## Basic
  get: ^4.6.6
  hive: ^2.2.3
  path_provider: ^2.1.2
  intl: ^0.19.0
  flutter_native_splash: ^2.3.13
  image_picker: ^1.0.7
  universal_html: ^2.2.4
  iconsax: ^0.0.8
  enefty_icons: ^1.0.7
  cupertino_icons: ^1.0.6
  image_network: ^2.5.6
  data_table_2: ^2.5.11
  flutter_spinbox: ^0.13.1
  custom_navigation_bar: ^0.8.2
  #-------------------------------------
  flutter_advanced_switch: ^3.1.0
  simple_animations: ^5.0.2
  flutter_typeahead: ^5.2.0
  photo_view: ^0.14.0
  #-------------------------------------
  ## Firebase
  firebase_core: ^2.27.1
  #  firebase_core_platform_interface: 4.5.2
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10
  firebase_auth: ^4.17.9
  #-------------------------------------
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.1.1
  twitter_login: ^4.4.2
  sign_in_with_apple: ^6.0.0
  crypto: ^3.0.3
  showcaseview: ^2.0.3
  #-------------------------------------
  ## Notifications
  awesome_notifications: ^0.9.3
  #-------------------------------------
  ## Map
  map_location_picker: ^1.2.8+3
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  # Map Key: AIzaSyC0fUYASQXlqfp1d5EFSIT7_0lg0_OIxq0
  #-------------------------------------

flutter_native_splash:
  color: '#EAF9F2'
  image:  assets/splash/splash_light.png
  color_dark: '#216869'
  image_dark: assets/splash/splash_dark.png
  android_12:
    image:  assets/splash/splash_light.png
    color: '#EAF9F2'
  fullscreen: true
  android: true
  ios: true
#  flutter pub run flutter_native_splash:create

dependency_overrides:
  js: ^0.7.1
  geolocator: ^11.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/splash/
    - assets/fonts/

#  fonts:
#    - family: Peosa
#      fonts:
#        - asset: assets/fonts/Peosa.ttf
#          style: normal
#          weight: 500